title: 福島肇のページ
description: My home page
author: "Hajime Fukushima"

theme: minima

base_url: /pages

# Minima social links
twitter_username: fukushimahaji
github_username: fukushimahj

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - frontpage.md
  - cv.md
  - paper.md
  - prt.md
  - [English](https://sites.google.com/view/fukushimahj-en)
#  - _pages/about.md
#  - _pages/archive.md

include:
#    - _pages

exclude: 
#    - .gitignore
#    - docker-compose.yml
#    - Gemfile
#    - Gemfile.lock
#    - LICENSE
#    - README.md
